### ISSUE TITLE
complex_model_300 specifically requires gpu:1

### ISSUE THREAD

**Issue by muntakimrafi** [autosome-ru/LegNet#1]
error message:

**RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.

**

have an easy fix. add map_location to torch.load in the test.py file
#initialize device
model.load_state_dict(torch.load(args.model, map_location=device))

**Comment by dmitrypenzar1996** [comment]
Thanks, we fixed the issue
